version: 2

sources:
  - name: raw_data
    database: CAPSTONE_PROJECT
    schema: SC_RAW
    loader: S3

    tables:
      - name: SC_WhCosts
        description: >
            This source table loads data of cost of storage per unit for each warehouse
                            
        external:
          location: "@s3_snow_stage"
          file_format: "csv_r_format"

        columns: 
          - name: WH
            data_type: varchar(9)
            description: Name of warehouse
          - name: "Cost/Unit"
            data_type: decimal(4,2)
            description: Cost of storage per unit

