
SELECT 
    CARRIER::VARCHAR(10) as CARRIER,
    ORIG_PORT::VARCHAR(10) as ORIGIN_PORT,
    DEST_PORT::VARCHAR(10) as DESTINATION_PORT,
    -- TO_NUMBER(MIN_WT_QTY) as MIN_WT_QTY
    MIN_WT_QTY::NUMBER as MIN_WT_QTY,
    MAX_WT_QTY::NUMBER as MAX_WT_QTY,
    SVC_CD::VARCHAR(5) as SERVICE_LEVEL,
    replace(MINIMUM_COST,'$','')::NUMBER as MINIMUM_COST,
    replace(RATE,'$','')::NUMBER as RATE,
    TRANSPORT_MODE:: VARCHAR(10) as TRANSPORT_MODE,
    TPT_DAY_CNT::INTEGER as TPT_DAY_CNT,
    CARRIER_TYPE::VARCHAR(40) as CARRIER_TYPE
FROM {{ref('raw_sc_freight_rates')}}